### ISSUE TITLE
Support other transition effects 

### ISSUE THREAD

**Issue by bradley-erickson** [pip-install-python/dash_swiper#1]
The only transition effect supported currently is `gl`. This package ought to support the other [transition effects](https://swiperjs.com/swiper-api#param-effect): `slide`, `fade`, `cube`, `coverflow`, `flip`, `creative`, or `cards`.

**Comment by pip-install-python** [comment]
Yeah, it's a substantial amount of work to add each new transition effect. Havent had the time, but gl offers 20 initial options. I'd probably need to make them their own packages rather than combining them in this repo to prevent conflict errors

**Comment by bradley-erickson** [comment]
Where can I find information about the `gl` options? I didn't see that option when digging through the Swiperjs documentation, but I may have missed it.

**Comment by pip-install-python** [comment]
https://community.plotly.com/t/pip-install-dash-swiper/83573

Currently only supports these transition effects: 

random

dots

flyeye

morph-x

morph-y

page-curl

peel-x

peel-y

polygons-fall

polygons-morph

polygons-wind

pixelize

ripple

shutters

slices

squares

stretch

wave-x

wind
